title: "AI Platforms With Multi-Agent Systems"
description: "An exploration of the transformative power of multi-agent AI systems, guiding businesses and developers in designing, deploying, and managing autonomous AI agents to enhance efficiency, scalability, and adaptability across various industries."
theme: "just-the-docs"

# Use the remote theme
remote_theme: pmarsceill/just-the-docs

# Point GitHub Pages to the /docs directory
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Enable documentation collection
collections:
  docs:
    permalink: "/:path/"
    output: true

# Navigation settings
nav_sort: case_insensitive

# Set /docs as the base directory (important for GitHub Pages)
baseurl: "/your-repo-name"
