title: "AI Platforms With Multi-Agent Systems"
description: "An exploration of the transformative power of multi-agent AI systems, guiding businesses and developers in designing, deploying, and managing autonomous AI agents to enhance efficiency, scalability, and adaptability across various industries."
theme: "just-the-docs"

# Use the remote theme
remote_theme: pmarsceill/just-the-docs

# Navigation settings
nav_sort: case_insensitive

# Set the base directory
baseurl: "/book-mas"

# Tell Jekyll to use the `/docs` directory as the source
source: docs

# Enable relative links for internal navigation
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
