title: AI Platforms With Multi-Agent Systems
description: An exploration of the transformative power of multi-agent AI systems, guiding businesses and developers in designing, deploying, and managing autonomous AI agents to enhance efficiency, scalability, and adaptability across various industries.

# Use a remote theme
remote_theme: just-the-docs/just-the-docs
search_enabled: true

# Navigation settings
nav_sort: case_insensitive

# URL settings
url: https://dragonscale-ai.github.io/book-mas/
baseurl: /book-mas

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# File handling
relative_links:
  enabled: true
  collections: true

# Color scheme
color_scheme: light # or dark

# Miscellaneous
enable_copy_code_button: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
